-- Leads Table
CREATE TABLE leads (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  message text,
  status text DEFAULT 'New',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Grant API access
GRANT SELECT, INSERT, UPDATE, DELETE ON leads TO anon;

-- Add policies
CREATE POLICY "Enable insert access for anon" ON leads FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Enable read access for anon" ON leads FOR SELECT TO anon USING (true);
CREATE POLICY "Enable update access for anon" ON leads FOR UPDATE TO anon USING (true);
CREATE POLICY "Enable delete access for anon" ON leads FOR DELETE TO anon USING (true);
