-- 1. Projects Table
CREATE TABLE projects (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text NOT NULL,
  price text NOT NULL,
  date text NOT NULL,
  city text NOT NULL,
  category text NOT NULL,
  img text NOT NULL,
  area text,
  bhk integer,
  amenities jsonb DEFAULT '[]'::jsonb
);

INSERT INTO projects (title, description, price, date, city, category, img, area, bhk, amenities) VALUES
('Skyline Penthouse', 'Ultra-luxury penthouse with panoramic city views.', '₹15.00 Cr', '2026', 'Noida', 'Flats', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80', '5,500 sq.ft.', 5, '["Private Pool", "Home Theater", "Smart Home"]'),
('Serene Villa', 'Modern minimalist villa surrounded by nature.', '₹8.50 Cr', '2025', 'Greater Noida', 'Villas', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', '4,200 sq.ft.', 4, '["Landscaped Garden", "Gym", "Security"]'),
('The Heritage', 'Classic colonial architecture blended with modern amenities.', '₹12.00 Cr', '2025', 'Delhi', 'Villas', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', '6,000 sq.ft.', 6, '["Courtyard", "Library", "Wine Cellar"]'),
('Urban Oasis', 'Premium apartments in the heart of the tech park.', '₹4.20 Cr', '2026', 'Noida', 'Flats', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', '2,800 sq.ft.', 3, '["Clubhouse", "Tennis Court", "Spa"]'),
('Riverside Estate', 'Spacious farmhouse with private river access.', '₹22.00 Cr', '2027', 'Garhmukteshwar', 'Farm House', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', '2 Acres', 5, '["Boat Dock", "Orchard", "Guest House"]'),
('Tech Hub Tower', 'Grade A commercial office space for modern enterprises.', '₹55.00 Cr', '2026', 'Noida', 'Commercial', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80', '25,000 sq.ft.', null, '["Food Court", "Helipad", "LEED Platinum"]');


-- 2. Agents Table
CREATE TABLE agents (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  role text NOT NULL,
  image text NOT NULL,
  bio text NOT NULL,
  top_performer boolean DEFAULT false,
  projects_delivered integer DEFAULT 0,
  client_rating text DEFAULT '5.0/5'
);

INSERT INTO agents (name, role, image, bio, top_performer, projects_delivered, client_rating) VALUES
('Rahul Sharma', 'Senior Principal Architect', 'https://randomuser.me/api/portraits/men/32.jpg', 'Award-winning architect with 15+ years of experience in sustainable urban design.', true, 45, '4.9/5'),
('Priya Patel', 'Lead Interior Designer', 'https://randomuser.me/api/portraits/women/44.jpg', 'Specializes in creating luxurious and functional interior spaces for commercial clients.', false, 38, '4.8/5'),
('Amit Kumar', 'Structural Engineer', 'https://randomuser.me/api/portraits/men/67.jpg', 'Expert in high-rise structural integrity and innovative construction methodologies.', false, 52, '4.9/5'),
('Sneha Gupta', 'Project Director', 'https://randomuser.me/api/portraits/women/68.jpg', 'Master of project execution, ensuring on-time delivery with zero compromise on quality.', false, 24, '5.0/5');


-- 3. Services Table
CREATE TABLE services (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text NOT NULL,
  icon_svg text NOT NULL
);

INSERT INTO services (title, description, icon_svg) VALUES
('Architectural Design', 'Award-winning architectural solutions that blend form, function, and future-ready sustainability. From residential to commercial skyscrapers.', '<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#4a8bfa" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21h18"></path><path d="M9 8h1"></path><path d="M9 12h1"></path><path d="M9 16h1"></path><path d="M14 8h1"></path><path d="M14 12h1"></path><path d="M14 16h1"></path><path d="M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16"></path></svg>'),
('Interior Design', 'Crafting bespoke interior spaces that reflect your personality or brand identity, focusing on spatial harmony and premium material selection.', '<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#4a8bfa" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>'),
('Urban Planning', 'Developing master plans for communities and cities that prioritize connectivity, green spaces, and sustainable growth.', '<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#4a8bfa" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20"></path><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>');


-- 4. Media Table
CREATE TABLE media_posts (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type text NOT NULL,
  title text NOT NULL,
  date text NOT NULL,
  read_time text NOT NULL,
  img text NOT NULL,
  description text NOT NULL,
  content text NOT NULL
);

INSERT INTO media_posts (type, title, date, read_time, img, description, content) VALUES
('News', 'ED Infratech Announces New Ultra-Luxury Project', 'June 05, 2026', '5 min read', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80', 'Expanding our footprint with a state-of-the-art hub.', 'Greater Noida is poised to see a monumental shift in luxury living...'),
('Blog', 'Why Vrindavan is Becoming the Top Destination', 'May 28, 2026', '7 min read', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', 'Discover the rising trend of luxury farmhouse investments.', 'Vrindavan is no longer just a spiritual getaway...'),
('Press Release', 'Award for Excellence in Sustainable Architecture', 'May 15, 2026', '3 min read', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80', 'Recognized globally for integrating smart eco-friendly features.', 'We are honored to announce that ED Infratech has been awarded...');


-- Set up Row Level Security (RLS) so anyone can read/write for now
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all" ON projects FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON projects FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all" ON projects FOR DELETE USING (true);

CREATE POLICY "Enable read access for all" ON agents FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON agents FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON agents FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all" ON agents FOR DELETE USING (true);

CREATE POLICY "Enable read access for all" ON services FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON services FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON services FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all" ON services FOR DELETE USING (true);

CREATE POLICY "Enable read access for all" ON media_posts FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON media_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON media_posts FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all" ON media_posts FOR DELETE USING (true);
