-- Company Overview Settings Table
CREATE TABLE company_overview_settings (
  id integer PRIMARY KEY,
  heading text NOT NULL,
  subheading text NOT NULL,
  stats_json jsonb NOT NULL,
  values_json jsonb NOT NULL
);

-- Testimonials Table
CREATE TABLE testimonials (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company text NOT NULL,
  subtitle text NOT NULL,
  logo text,
  review_text text NOT NULL,
  box_color text DEFAULT '#ffee00'
);

-- Methodology Settings Table
CREATE TABLE methodology_settings (
  id integer PRIMARY KEY,
  heading text NOT NULL,
  subheading text NOT NULL,
  circle1_title text NOT NULL,
  circle1_desc text NOT NULL,
  circle2_title text NOT NULL,
  circle2_desc text NOT NULL,
  circle3_title text NOT NULL,
  circle3_desc text NOT NULL
);

-- Site Settings Table
CREATE TABLE site_settings (
  id integer PRIMARY KEY,
  contact_email text NOT NULL,
  contact_phone text NOT NULL,
  contact_address text NOT NULL,
  facebook_url text,
  instagram_url text,
  linkedin_url text
);

-- Insert Default Values

INSERT INTO company_overview_settings (id, heading, subheading, stats_json, values_json)
VALUES (
  1, 
  'Transform A Space for Work, Into A Space for Life',
  'ED Infratech is a reliable interior designer & builder in Singapore that provides integrated services for industrial / office & retail spaces.',
  '[{"value": "20+", "label": "Years Of Experience"}, {"value": "08", "label": "Global Offices In Asia Pacific"}, {"value": "3M", "label": "SQM Project Completed"}]',
  '[{"num": "01", "title": "Experience", "desc": "More than 20 years of experiences in interior fit-out field"}, {"num": "02", "title": "Expansion", "desc": "8 regional offices around Asia Pacific"}, {"num": "03", "title": "Reliable", "desc": "Accountability and creditability"}, {"num": "04", "title": "Performance", "desc": "Solid track record"}]'
);

INSERT INTO testimonials (company, subtitle, logo, review_text, box_color) VALUES 
('DLF Limited', 'DESIGN | BUILD', 'https://logo.clearbit.com/dlf.in', 'ED Infratech transformed our commercial spaces with exceptional quality. Their attention to detail and commitment to timelines perfectly align with DLF''s standards of excellence.', '#ffee00'),
('M3M India', 'INTERIOR FIT-OUT', 'https://logo.clearbit.com/m3mindia.com', 'Working with ED Infratech on our luxury residential and commercial projects has been a seamless experience. They bring innovative design solutions that elevate the overall aesthetic.', '#ffffff'),
('Omaxe', 'WORKSPACE DESIGN', 'https://logo.clearbit.com/omaxe.com', 'The team at ED Infratech successfully interpreted our vision for modern, collaborative workspaces. Their execution is flawless, delivering premium quality consistently.', '#ffee00');

INSERT INTO methodology_settings (id, heading, subheading, circle1_title, circle1_desc, circle2_title, circle2_desc, circle3_title, circle3_desc)
VALUES (
  1,
  'Bold Design. Clear Strategy. Dependable Results.',
  'ED Infratech is founded upon the idea of providing first-rate quality design & construction work tailored to each client''s specific needs.',
  'Verified Properties', 'Carefully screened listings from trusted builders across premium locations.',
  'Strategic Investments', 'Helping you choose properties with strong growth and future value.',
  'Trusted Partnerships', 'Connected with reliable developers to deliver secure property deals.'
);

INSERT INTO site_settings (id, contact_email, contact_phone, contact_address, facebook_url, instagram_url, linkedin_url)
VALUES (
  1,
  'contact@edinfratech.com',
  '+91 9876543210',
  '123, ED Infratech Tower, Sector 62, Noida, UP, India',
  'https://facebook.com',
  'https://instagram.com',
  'https://linkedin.com'
);

-- Enable RLS
ALTER TABLE company_overview_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE methodology_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Grant API access
GRANT SELECT, INSERT, UPDATE, DELETE ON company_overview_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON testimonials TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON methodology_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON site_settings TO anon;

-- Add policies
CREATE POLICY "Enable read access for anon" ON company_overview_settings FOR SELECT TO anon USING (true);
CREATE POLICY "Enable update access for anon" ON company_overview_settings FOR UPDATE TO anon USING (true);
CREATE POLICY "Enable insert access for anon" ON company_overview_settings FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable read access for anon" ON testimonials FOR SELECT TO anon USING (true);
CREATE POLICY "Enable update access for anon" ON testimonials FOR UPDATE TO anon USING (true);
CREATE POLICY "Enable insert access for anon" ON testimonials FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Enable delete access for anon" ON testimonials FOR DELETE TO anon USING (true);

CREATE POLICY "Enable read access for anon" ON methodology_settings FOR SELECT TO anon USING (true);
CREATE POLICY "Enable update access for anon" ON methodology_settings FOR UPDATE TO anon USING (true);
CREATE POLICY "Enable insert access for anon" ON methodology_settings FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable read access for anon" ON site_settings FOR SELECT TO anon USING (true);
CREATE POLICY "Enable update access for anon" ON site_settings FOR UPDATE TO anon USING (true);
CREATE POLICY "Enable insert access for anon" ON site_settings FOR INSERT TO anon WITH CHECK (true);
